"""Remove unique from currency in Output

Revision ID: 043890a23408
Revises: ea1a5b5a6936
Create Date: 2024-10-20 13:56:09.771324

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "043890a23408"
down_revision: Union[str, None] = "ea1a5b5a6936"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_service_outputs_currency", table_name="service_outputs")
    op.create_index(
        op.f("ix_service_outputs_currency"),
        "service_outputs",
        ["currency"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrading this change will create an error, so let's do nothing instead"""
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_service_outputs_currency'), table_name='service_outputs')
    # op.create_index('ix_service_outputs_currency', 'service_outputs', ['currency'], unique=True)
    # # ### end Alembic commands ###
    pass
