"""Add token height and blockhash

Revision ID: 096f34712b34
Revises: 607a89437c96
Create Date: 2025-11-12 04:30:42.733456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '096f34712b34'
down_revision: Union[str, None] = '607a89437c96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_tokens', sa.Column('height', sa.Integer(), nullable=False))
    op.add_column('service_tokens', sa.Column('blockhash', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_service_tokens_blockhash'), 'service_tokens', ['blockhash'], unique=False)
    op.create_index(op.f('ix_service_tokens_height'), 'service_tokens', ['height'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_tokens_height'), table_name='service_tokens')
    op.drop_index(op.f('ix_service_tokens_blockhash'), table_name='service_tokens')
    op.drop_column('service_tokens', 'blockhash')
    op.drop_column('service_tokens', 'height')
    # ### end Alembic commands ###
