"""Add mempool model

Revision ID: 1ed2a26c076f
Revises: 9dd5b5ff53f4
Create Date: 2025-02-15 00:46:06.621735

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1ed2a26c076f"
down_revision: Union[str, None] = "9dd5b5ff53f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service_mempool",
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column(
            "raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("service_mempool")
    # ### end Alembic commands ###
