"""Change Token.type datatype to string

Revision ID: 209810ecde3a
Revises: cc3da8897988
Create Date: 2024-10-21 14:42:28.219808

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "209810ecde3a"
down_revision: Union[str, None] = "cc3da8897988"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "service_tokens",
        "type",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_service_tokens_type"), "service_tokens", ["type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrading these changes would break the execution of alembic's migrations. So we will do nothing"""
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_service_tokens_type'), table_name='service_tokens')
    # op.alter_column('service_tokens', 'type',
    #            existing_type=sa.String(length=64),
    #            type_=sa.INTEGER(),
    #            existing_nullable=False)
    # # ### end Alembic commands ###
