"""Add fee in Transaction

Revision ID: 2f8d9aa30f4a
Revises: f8e7eb0e002f
Create Date: 2025-11-11 18:01:13.984544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f8d9aa30f4a'
down_revision: Union[str, None] = 'f8e7eb0e002f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_transactions', sa.Column('fee', sa.Numeric(precision=28, scale=8), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_transactions', 'fee')
    # ### end Alembic commands ###
