"""Add locked balance to AddressBalance

Revision ID: 37702ef0ffc1
Revises: 784bfcfbea36
Create Date: 2025-10-22 12:51:30.281142

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "37702ef0ffc1"
down_revision: Union[str, None] = "784bfcfbea36"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_address_balances",
        sa.Column("locked", sa.Numeric(precision=28, scale=8), nullable=False),
    )
    op.add_column(
        "service_transactions", sa.Column("coinbase", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_transactions", "coinbase")
    op.drop_column("service_address_balances", "locked")
    # ### end Alembic commands ###
