"""Add Output.unlocked column and Output.timelock, Output.spent indexes

Revision ID: 4fdb6637c28c
Revises: 37702ef0ffc1
Create Date: 2025-10-25 06:33:11.608583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fdb6637c28c'
down_revision: Union[str, None] = '37702ef0ffc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_outputs', sa.Column('unlocked', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_service_outputs_spent'), 'service_outputs', ['spent'], unique=False)
    op.create_index(op.f('ix_service_outputs_timelock'), 'service_outputs', ['timelock'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_outputs_timelock'), table_name='service_outputs')
    op.drop_index(op.f('ix_service_outputs_spent'), table_name='service_outputs')
    op.drop_column('service_outputs', 'unlocked')
    # ### end Alembic commands ###
