"""Add block reward calculation

Revision ID: 607a89437c96
Revises: 2f8d9aa30f4a
Create Date: 2025-11-11 18:55:33.213381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '607a89437c96'
down_revision: Union[str, None] = '2f8d9aa30f4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_blocks', sa.Column('reward', sa.Numeric(precision=28, scale=8), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_blocks', 'reward')
    # ### end Alembic commands ###
