"""Add id to source transaction in input model

Revision ID: 64ed9228c710
Revises: 80c7de8368f4
Create Date: 2025-01-30 13:25:07.958019

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "64ed9228c710"
down_revision: Union[str, None] = "80c7de8368f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_inputs",
        sa.Column("source_txid", sa.String(length=64), nullable=False),
    )
    op.create_index(
        op.f("ix_service_inputs_source_txid"),
        "service_inputs",
        ["source_txid"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_service_inputs_source_txid"), table_name="service_inputs"
    )
    op.drop_column("service_inputs", "source_txid")
    # ### end Alembic commands ###
