"""remove height from mempool

Revision ID: 784bfcfbea36
Revises: 1ed2a26c076f
Create Date: 2025-02-16 19:22:46.170172

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "784bfcfbea36"
down_revision: Union[str, None] = "1ed2a26c076f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_mempool", "height")
    # ### end Alembic commands ###


def downgrade() -> None:
    # We do not need to re-create this column
    # Also, it would break, because it was not null
    ...
