"""Add script and asm columns into outputs model

Revision ID: 9dd5b5ff53f4
Revises: 64ed9228c710
Create Date: 2025-02-13 00:06:06.082818

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9dd5b5ff53f4"
down_revision: Union[str, None] = "64ed9228c710"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_outputs", sa.Column("script", sa.String(), nullable=False)
    )
    op.add_column(
        "service_outputs", sa.Column("asm", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_outputs", "asm")
    op.drop_column("service_outputs", "script")
    # ### end Alembic commands ###
