"""Add size, locktime, version columns to Transaction

Revision ID: ea1a5b5a6936
Revises: 01b935993dac
Create Date: 2024-10-20 13:54:02.371040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea1a5b5a6936'
down_revision: Union[str, None] = '01b935993dac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_outputs', sa.Column('type', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_service_outputs_type'), 'service_outputs', ['type'], unique=False)
    op.add_column('service_transactions', sa.Column('size', sa.Integer(), nullable=False))
    op.add_column('service_transactions', sa.Column('locktime', sa.Integer(), nullable=False))
    op.add_column('service_transactions', sa.Column('version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_transactions', 'version')
    op.drop_column('service_transactions', 'locktime')
    op.drop_column('service_transactions', 'size')
    op.drop_index(op.f('ix_service_outputs_type'), table_name='service_outputs')
    op.drop_column('service_outputs', 'type')
    # ### end Alembic commands ###
