[default]
    [default.database]
    endpoint = "postgresql+asyncpg://user:password@localhost:5432/boilerplate"

[testing]
    [testing.database]
    endpoint = "postgresql+asyncpg://user:password@localhost:5432/boilerplate-tests"
